# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdlr" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a856042c38d1f660a63915a2ec8836c0056888383ccb15844410b67033b438c2"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fdba0e28032da598022f8e7002ca84d39aefbf16531b849e0904cc2c1343f34f"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mdlr"
  desc "Polyglot code-analysis tool that builds a graph of source-level units and computes structural metrics"
  homepage "https://github.com/thempatel/mdlr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdlr"
  binary "mdlr-extract-go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr-extract-go"]
    end
  end

  # No zap stanza required

end
