# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdlr" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "534a23f27aa5de42b85bebd325c6f05ea375d8ff76825d535e99e3eee9c994bc"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "33c85ba513fa3b234e2c37c84cbab04a85fa86afb8b34c2f8a0ea30fa09062bb"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mdlr"
  desc "Polyglot code-analysis tool that builds a graph of source-level units and computes structural metrics"
  homepage "https://github.com/thempatel/mdlr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdlr"
  binary "mdlr-extract-go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr-extract-go"]
    end
  end

  # No zap stanza required

end
