# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdlr" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "7db882b928374a06260914c64478637553ea7fb61ff6772eab4228a1125234d9"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60909d4a2e4d4f355b993ee137c2a0547a2b0810b30b7d48b5256dc02f96fcc8"
      url "https://github.com/thempatel/mdlr/releases/download/v#{version}/mdlr_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mdlr"
  desc "Polyglot code-analysis tool that builds a graph of source-level units and computes structural metrics"
  homepage "https://github.com/thempatel/mdlr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdlr"
  binary "mdlr-extract-go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdlr-extract-go"]
    end
  end

  # No zap stanza required

end
